First actual running draft on thoth

diff --git a/run-thoth-vm b/run-thoth-vm
--- a/run-thoth-vm
+++ b/run-thoth-vm
@@ -1,27 +1,9 @@
 #!/usr/bin/env bash
 
-function buildOnePort() {
-    local port=$1
-    return "hostfwd=::${port}-:${port}"
-}
+set -e # Exit on error
+vmname="thoth"
+export QEMU_NET_OPTS="hostfwd=::2121-:21,hostfwd=::2222-:22,hostfwd=::4533-:4533"
 
-function buildPorts() {
-    local ports=("$@")
-    local portCommand=""
-    for port in "${ports[@]}"; do
-        portCommand="${portCommand}$(buildOnePort $port),"
-    done
-    echo "${portCommand::-1}"
-}
-
-vmname = "thoth"
-ports = (
-    21 # FTP
-    22 # SSH
-    4533 # Navidrome
-)
-portCommand = $(buildPorts $ports)
-
-nixos-rebuild build-vm .\#$vmname
+nixos-rebuild build-vm --flake .\#$vmname
 rm -f $vmname.qcow2
-QEMU_NET_OPTS=$portCommand ./result/bin/run-$vmname-vm
+./result/bin/run-$vmname-vm
